Add MoLeRGenerator model
microsoft/molecule-generation pull request #6
Opened 2022-04-11 13:10 UTC by sarahnlewis

Add the MoLeRGenerator model which samples molecules autoregressively using the MoLeR decoder. Refactor MoLeRVae so that I can do this without too much code duplication.

2022-04-12 21:13 UTC, sarahnlewis commented on molecule_generation/models/moler_generator.py
> +        )
Done

2022-04-12 21:13 UTC, sarahnlewis commented on molecule_generation/models/moler_base_model.py
> +        )
Fixed

2022-04-12 21:13 UTC, sarahnlewis commented on molecule_generation/models/moler_base_model.py
> +                # Actually, we set this vector to all-zeros, but leave it for ease of reuse of MoLeR VAE code
I rewrote this comment.

2022-04-12 21:14 UTC, sarahnlewis commented on molecule_generation/layers/moler_decoder.py
>      ) -> Iterable[
Fixed. This was just a failure to finish tidying up, sorry.

2022-04-12 21:37 UTC, sarahnlewis commented on molecule_generation/cli/train.py
> +)
If I'm looking at the right runs for [MoLeRGenerator](https://ml.azure.com/experiments/id/23a4f4bf-25f6-4dcf-9759-39867ae90904/runs/2fe67777-f793-4859-bde1-084b5d0309bf?wsid=/subscriptions/681d5936-9572-4a8f-aa6f-8f9d42a8abc4/resourceGroups/genchem_ci/providers/Microsoft.MachineLearningServices/workspaces/genchem_ci&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#) and [MoLeRVae](https://ml.azure.com/runs/d5bed37d-7456-4239-a9c1-a9119c801f85?wsid=/subscriptions/681d5936-9572-4a8f-aa6f-8f9d42a8abc4/resourceGroups/genchem_ci/providers/Microsoft.MachineLearningServices/workspaces/genchem_ci&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#) then MoLeRVae and MoLeRGenerator do similarly on FCD and KL divergence, but MoLeRGenerator does badly on uniqueness and novelty.

2022-04-14 13:57 UTC, kmaziarz requested changes
LGTM, thanks!

(I took a final pass, only noting a few small nitpicks. The ones related to import order/grouping aren't enforced in CI yet, but _mostly_ followed in _most_ files...)

2022-04-14 13:57 UTC, kmaziarz commented on molecule_generation/cli/train.py
>              f"This training script can only work with CGVAE/MoLeRVae, "
```suggestion
            f"This training script can only work with CGVAE/MoLeR, "
```

2022-04-14 13:57 UTC, kmaziarz commented on molecule_generation/models/moler_vae.py
> +from molecule_generation.models.moler_base_model import MoLeRBaseModel
nit: put this together with the other `from molecule_generation` imports

2022-04-14 13:57 UTC, kmaziarz commented on molecule_generation/test/models/test_moler_vae.py
>  from molecule_generation.models.moler_vae import MoLeRVae
nit: sort imports
```suggestion
from molecule_generation.dataset.jsonl_moler_trace_dataset import JSONLMoLeRTraceDataset
from molecule_generation.models.moler_generator import MoLeRGenerator
from molecule_generation.models.moler_vae import MoLeRVae
```

2022-04-14 13:57 UTC, kmaziarz commented on molecule_generation/utils/model_utils.py
>  from molecule_generation.dataset.in_memory_trace_dataset import InMemoryTraceDataset
nit: sort imports
```suggestion
from molecule_generation.dataset.in_memory_trace_dataset import InMemoryTraceDataset
from molecule_generation.models.cgvae import CGVAE
from molecule_generation.models.moler_generator import MoLeRGenerator
from molecule_generation.models.moler_vae import MoLeRVae
```

2022-04-14 13:57 UTC, kmaziarz commented on molecule_generation/utils/model_utils.py
>          raise ValueError(f"Model loaded from {trained_model_path} not a CGVAE or MoLeRVae model!")
```suggestion
        raise ValueError(f"Model loaded from {trained_model_path} not a CGVAE or MoLeR model!")
```

2022-04-14 13:57 UTC, kmaziarz commented on molecule_generation/utils/moler_inference_server.py
>  from molecule_generation.utils.moler_decoding_utils import MoLeRDecoderState
nit: sort and combine imports
```suggestion
from molecule_generation.dataset.in_memory_trace_dataset import InMemoryTraceDataset, DataFold
from molecule_generation.models.moler_generator import MoLeRGenerator
from molecule_generation.models.moler_vae import MoLeRVae
from molecule_generation.utils.moler_decoding_utils import DecoderSamplingMode, MoLeRDecoderState
```

2022-04-14 15:57 UTC, sarahnlewis commented on molecule_generation/models/moler_vae.py
> +from molecule_generation.models.moler_base_model import MoLeRBaseModel
Done

2022-04-14 17:50 UTC, kmaziarz approved these changes

2022-04-14 22:57 UTC, kmaziarz commented
Actually, one more thing: I guess we need to update `README.md` to replace the uses of `ModelWrapper` with `VaeWrapper`, as the former is now an abstract base class that cannot be instantiated?

2022-04-19 09:16 UTC, sarahnlewis commented
> Actually, one more thing: I guess we need to update `README.md` to replace the uses of `ModelWrapper` with `VaeWrapper`, as the former is now an abstract base class that cannot be instantiated?

Done. I also added `VaeWrapper` and `GeneratorWrapper` to `__init__.py`.

2022-04-19 09:29 UTC, merged